name: LobbySpravne
version: '${project.version}'
main: cz.cvut.fel.pjv.stolbajakub.lobbyspravne.LobbySpravne
api-version: '1.20'
commands:
  spawn:
    description: "teleport to spawn/set spawn"
    usage: "/spawn (set x y z)"
    aliases: [spawn]
    permission:
    permission-message: "You do not have permission to use this command"