name: Lobby
version: '${project.version}'
main: cz.cvut.fel.pjv.stolbajakub.Lobby
api-version: '1.20'
commands:
  spawn:
    description: "teleport to spawn/set spawn"
    usage: "/spawn (set x y z)"
    aliases:
    permission:
    permission-message: "You do not have permission to use this command"
#channels: [BungeeCord, "bedwars:tolobbyinfo"]
