name: Myperms
version: '1.0-SNAPSHOT'
main: cz.cvut.fel.pjv.stolbajakub.myperms.Myperms
api-version: '1.20'
commands:
  myperms:
    description: "go see documentation"
    usage: "/myperms add/rem/check player permission"
    aliases:
    permission: "myperms.set.perms"
    permission-message: "You do not have permission to use this command"
