name: Lobby
version: '${project.version}'
main: cz.cvut.fel.pjv.stolbajakub.Lobby
api-version: '1.20'
commands:
  spawn:
    description: "teleport to spawn/set spawn"
    usage: "/spawn (set x y z)"
    aliases:
    permission:
    permission-message: "You do not have permission to use this command"
  myperms:
    description: "go see documentation"
    usage: "/myperms add/rem/check player permission"
    aliases:
    permission: "lobby.set.perms"
    permission-message: "You do not have permission to use this command"
